- name: Check if Helm is installed
  shell: helm version --short
  register: helm_version
  ignore_errors: true
  changed_when: false

- name: Download and install Helm
  block:

    - name: Download Helm installation script
      shell: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3

    - name: Make the script executable
      shell: chmod 700 get_helm.sh

    - name: Run the Helm installation script
      shell: bash ./get_helm.sh
      
  when: helm_version.rc != 0