---
- name: Deploy k3s masters
  hosts: master
  vars_files:
    - group_vars/vars.yml
  roles:
    - prereqs
    - k3s_master

- name: Deploy k3s workers
  hosts: agents
  vars_files:
    - group_vars/vars.yml
  roles:
    - prereqs
    - k3s_agent