---
- import_playbook: deploy_k3s.yml
- import_playbook: deploy_helm.yml
- import_playbook: deploy_metallb.yml
- import_playbook: deploy_nginx.yml
- import_playbook: deploy_jetstack.yml
- import_playbook: deploy_rancher.yml
#- import_playbook: deploy_sharedstorage.yml
