---
- name: Check if K3s is installed
  stat:
    path: /usr/local/bin/k3s 
  register: k3s_check

- name: Install K3s
  shell: |
    curl -sfL https://get.k3s.io | \
      K3S_TOKEN={{ k3s_token }} \
      INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 \
      --disable=traefik \
      --disable-cloud-controller \
      --disable=servicelb \
      --flannel-backend=host-gw" sh -s
  register: k3s_master_installation
  when: not k3s_check.stat.exists

- name: Check if K3s installation was successful
  assert:
    that:
      - k3s_master_installation.rc == 0
    fail_msg: "K3s installation failed!"
  when: not k3s_check.stat.exists
