---
- name: Check if K3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: k3s_check
  
- name: Set K3S_Server variable
  set_fact:
    k3s_server: "{{ groups['master'][0] }}"
  when: not k3s_check.stat.exists

- name: Install K3s Agents
  shell: |
    curl -sfL https://get.k3s.io | \
        K3S_TOKEN={{ k3s_token }} \
        K3S_URL=https://{{ k3s_server }}:6443 sh -s -
  when: not k3s_check.stat.exists